'use client';

import { useState } from 'react';
import { Check, Copy, ChevronDown, ChevronUp } from 'lucide-react';

interface Font {
    path: string;
    fileName: string;
    cdnUrl: string;
    format: string;
    familyName: string;
    weight: number;
    style: string;
}

interface CSSGeneratorProps {
    fonts: Font[];
    repoFullName: string;
}

export function CSSGenerator({ fonts, repoFullName }: CSSGeneratorProps) {
    const [copied, setCopied] = useState(false);
    const [expanded, setExpanded] = useState(true);

    const families = fonts.reduce((acc, font) => {
        if (!acc[font.familyName]) acc[font.familyName] = [];
        acc[font.familyName].push(font);
        return acc;
    }, {} as Record<string, Font[]>);

    const generateCSS = () => {
        let css = `/* Fonts from ${repoFullName} - Generated by Webfont CDN */\n\n`;
        for (const [family, familyFonts] of Object.entries(families)) {
            for (const font of familyFonts) {
                css += `@font-face {
  font-family: '${family}';
  src: url('${font.cdnUrl}') format('${font.format === 'woff2' ? 'woff2' : font.format === 'woff' ? 'woff' : font.format === 'ttf' ? 'truetype' : 'opentype'}');
  font-weight: ${font.weight};
  font-style: ${font.style};
  font-display: swap;
}\n\n`;
            }
        }
        return css.trim();
    };

    const fullCSS = generateCSS();

    const copyToClipboard = async () => {
        await navigator.clipboard.writeText(fullCSS);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
    };

    if (fonts.length === 0) return null;

    return (
        <div className="bg-white dark:bg-slate-800/50 rounded-2xl border border-slate-200 dark:border-slate-700 overflow-hidden">
            <button
                onClick={() => setExpanded(!expanded)}
                className="w-full flex items-center justify-between p-4 text-left hover:bg-slate-50 dark:hover:bg-slate-700/50 transition-colors"
            >
                <div>
                    <h3 className="text-lg font-semibold text-slate-900 dark:text-white">Complete CSS</h3>
                    <p className="text-sm text-slate-500 dark:text-slate-400">
                        {fonts.length} font{fonts.length !== 1 ? 's' : ''} • {Object.keys(families).length} famil{Object.keys(families).length !== 1 ? 'ies' : 'y'}
                    </p>
                </div>
                {expanded ? <ChevronUp className="w-5 h-5 text-slate-400" /> : <ChevronDown className="w-5 h-5 text-slate-400" />}
            </button>

            {expanded && (
                <div className="border-t border-slate-200 dark:border-slate-700">
                    <div className="relative">
                        <pre className="p-4 text-sm text-slate-600 dark:text-slate-300 font-mono overflow-x-auto max-h-80 bg-slate-50 dark:bg-slate-900/50">
                            {fullCSS}
                        </pre>
                        <button
                            onClick={copyToClipboard}
                            className="absolute top-3 right-3 flex items-center gap-2 px-4 py-2 text-sm font-medium text-white bg-sky-500 hover:bg-sky-600 rounded-xl transition-colors shadow-lg"
                        >
                            {copied ? <><Check className="w-4 h-4" /> Copied!</> : <><Copy className="w-4 h-4" /> Copy All</>}
                        </button>
                    </div>
                </div>
            )}
        </div>
    );
}
